manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: bortoz
      url-base: https://github.com/bortoz
  projects:
    - name: zmk
      remote: bortoz
      revision: backlight
      import: app/west.yml
  self:
    path: config
